package entities;
// Generated Mar 16, 2018 1:43:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeTai generated by hbm2java
 */
@Entity
@Table(name="de_tai"
    ,catalog="doantotnghiep"
)
public class DeTai  implements java.io.Serializable {


     private Integer maDeTai;
     private CongTy congTy;
     private GiangVienHuongDan giangVienHuongDan;
     private String tenDeTai;
     private String noiDung;
     private String yeuCau;
     private String nguoiDang;
     private int soLuong;
     private Integer soLuongCon;
     private Integer trangThai;
     private Set<SinhVienThucTap> sinhVienThucTaps = new HashSet<SinhVienThucTap>(0);

    public DeTai() {
    }

	
    public DeTai(CongTy congTy, GiangVienHuongDan giangVienHuongDan, String tenDeTai, String noiDung, String yeuCau, int soLuong) {
        this.congTy = congTy;
        this.giangVienHuongDan = giangVienHuongDan;
        this.tenDeTai = tenDeTai;
        this.noiDung = noiDung;
        this.yeuCau = yeuCau;
        this.soLuong = soLuong;
    }
    public DeTai(CongTy congTy, GiangVienHuongDan giangVienHuongDan, String tenDeTai, String noiDung, String yeuCau, String nguoiDang, int soLuong, Integer soLuongCon, Integer trangThai, Set<SinhVienThucTap> sinhVienThucTaps) {
       this.congTy = congTy;
       this.giangVienHuongDan = giangVienHuongDan;
       this.tenDeTai = tenDeTai;
       this.noiDung = noiDung;
       this.yeuCau = yeuCau;
       this.nguoiDang = nguoiDang;
       this.soLuong = soLuong;
       this.soLuongCon = soLuongCon;
       this.trangThai = trangThai;
       this.sinhVienThucTaps = sinhVienThucTaps;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ma_de_tai", unique=true, nullable=false)
    public Integer getMaDeTai() {
        return this.maDeTai;
    }
    
    public void setMaDeTai(Integer maDeTai) {
        this.maDeTai = maDeTai;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ma_cong_ty", nullable=false)
    public CongTy getCongTy() {
        return this.congTy;
    }
    
    public void setCongTy(CongTy congTy) {
        this.congTy = congTy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ma_gvhd", nullable=false)
    public GiangVienHuongDan getGiangVienHuongDan() {
        return this.giangVienHuongDan;
    }
    
    public void setGiangVienHuongDan(GiangVienHuongDan giangVienHuongDan) {
        this.giangVienHuongDan = giangVienHuongDan;
    }

    
    @Column(name="ten_de_tai", nullable=false, length=500)
    public String getTenDeTai() {
        return this.tenDeTai;
    }
    
    public void setTenDeTai(String tenDeTai) {
        this.tenDeTai = tenDeTai;
    }

    
    @Column(name="noi_dung", nullable=false, length=65535)
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }

    
    @Column(name="yeu_cau", nullable=false, length=65535)
    public String getYeuCau() {
        return this.yeuCau;
    }
    
    public void setYeuCau(String yeuCau) {
        this.yeuCau = yeuCau;
    }

    
    @Column(name="nguoi_dang")
    public String getNguoiDang() {
        return this.nguoiDang;
    }
    
    public void setNguoiDang(String nguoiDang) {
        this.nguoiDang = nguoiDang;
    }

    
    @Column(name="so_luong", nullable=false)
    public int getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }

    
    @Column(name="so_luong_con")
    public Integer getSoLuongCon() {
        return this.soLuongCon;
    }
    
    public void setSoLuongCon(Integer soLuongCon) {
        this.soLuongCon = soLuongCon;
    }

    
    @Column(name="trang_thai")
    public Integer getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(Integer trangThai) {
        this.trangThai = trangThai;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="deTai")
    public Set<SinhVienThucTap> getSinhVienThucTaps() {
        return this.sinhVienThucTaps;
    }
    
    public void setSinhVienThucTaps(Set<SinhVienThucTap> sinhVienThucTaps) {
        this.sinhVienThucTaps = sinhVienThucTaps;
    }




}


