package entities;
// Generated Mar 16, 2018 1:43:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name="login"
    ,catalog="doantotnghiep"
)
public class Login  implements java.io.Serializable {


     private String email;
     private String pass;
     private int rule;
     private Set<ThongBao> thongBaos = new HashSet<ThongBao>(0);
     private Set<SinhVien> sinhViens = new HashSet<SinhVien>(0);
     private Set<GiangVienHuongDan> giangVienHuongDans = new HashSet<GiangVienHuongDan>(0);
     private Set<DaiDienCongTy> daiDienCongTies = new HashSet<DaiDienCongTy>(0);
     private Set<Logs> logses = new HashSet<Logs>(0);
     private Set<GiangVienPhuTrach> giangVienPhuTraches = new HashSet<GiangVienPhuTrach>(0);
     private Set<Email> emails = new HashSet<Email>(0);

    public Login() {
    }

	
    public Login(String email, String pass, int rule) {
        this.email = email;
        this.pass = pass;
        this.rule = rule;
    }
    public Login(String email, String pass, int rule, Set<ThongBao> thongBaos, Set<SinhVien> sinhViens, Set<GiangVienHuongDan> giangVienHuongDans, Set<DaiDienCongTy> daiDienCongTies, Set<Logs> logses, Set<GiangVienPhuTrach> giangVienPhuTraches, Set<Email> emails) {
       this.email = email;
       this.pass = pass;
       this.rule = rule;
       this.thongBaos = thongBaos;
       this.sinhViens = sinhViens;
       this.giangVienHuongDans = giangVienHuongDans;
       this.daiDienCongTies = daiDienCongTies;
       this.logses = logses;
       this.giangVienPhuTraches = giangVienPhuTraches;
       this.emails = emails;
    }
   
     @Id 

    
    @Column(name="email", unique=true, nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="pass", nullable=false)
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }

    
    @Column(name="rule", nullable=false)
    public int getRule() {
        return this.rule;
    }
    
    public void setRule(int rule) {
        this.rule = rule;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="login")
    public Set<ThongBao> getThongBaos() {
        return this.thongBaos;
    }
    
    public void setThongBaos(Set<ThongBao> thongBaos) {
        this.thongBaos = thongBaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="login")
    public Set<SinhVien> getSinhViens() {
        return this.sinhViens;
    }
    
    public void setSinhViens(Set<SinhVien> sinhViens) {
        this.sinhViens = sinhViens;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="login")
    public Set<GiangVienHuongDan> getGiangVienHuongDans() {
        return this.giangVienHuongDans;
    }
    
    public void setGiangVienHuongDans(Set<GiangVienHuongDan> giangVienHuongDans) {
        this.giangVienHuongDans = giangVienHuongDans;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="login")
    public Set<DaiDienCongTy> getDaiDienCongTies() {
        return this.daiDienCongTies;
    }
    
    public void setDaiDienCongTies(Set<DaiDienCongTy> daiDienCongTies) {
        this.daiDienCongTies = daiDienCongTies;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="login")
    public Set<Logs> getLogses() {
        return this.logses;
    }
    
    public void setLogses(Set<Logs> logses) {
        this.logses = logses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="login")
    public Set<GiangVienPhuTrach> getGiangVienPhuTraches() {
        return this.giangVienPhuTraches;
    }
    
    public void setGiangVienPhuTraches(Set<GiangVienPhuTrach> giangVienPhuTraches) {
        this.giangVienPhuTraches = giangVienPhuTraches;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="login")
    public Set<Email> getEmails() {
        return this.emails;
    }
    
    public void setEmails(Set<Email> emails) {
        this.emails = emails;
    }




}


