package entities;
// Generated Mar 16, 2018 1:43:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SinhVienThucTap generated by hbm2java
 */
@Entity
@Table(name="sinh_vien_thuc_tap"
    ,catalog="doantotnghiep"
)
public class SinhVienThucTap  implements java.io.Serializable {


     private Integer id;
     private DeTai deTai;
     private SinhVien sinhVien;
     private Date thoiGianBatDau;
     private Date thoiGianKetThuc;
     private boolean trangThai;

    public SinhVienThucTap() {
    }

	
    public SinhVienThucTap(DeTai deTai, SinhVien sinhVien, boolean trangThai) {
        this.deTai = deTai;
        this.sinhVien = sinhVien;
        this.trangThai = trangThai;
    }
    public SinhVienThucTap(DeTai deTai, SinhVien sinhVien, Date thoiGianBatDau, Date thoiGianKetThuc, boolean trangThai) {
       this.deTai = deTai;
       this.sinhVien = sinhVien;
       this.thoiGianBatDau = thoiGianBatDau;
       this.thoiGianKetThuc = thoiGianKetThuc;
       this.trangThai = trangThai;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ma_de_tai", nullable=false)
    public DeTai getDeTai() {
        return this.deTai;
    }
    
    public void setDeTai(DeTai deTai) {
        this.deTai = deTai;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mssv", nullable=false)
    public SinhVien getSinhVien() {
        return this.sinhVien;
    }
    
    public void setSinhVien(SinhVien sinhVien) {
        this.sinhVien = sinhVien;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="thoi_gian_bat_dau", length=10)
    public Date getThoiGianBatDau() {
        return this.thoiGianBatDau;
    }
    
    public void setThoiGianBatDau(Date thoiGianBatDau) {
        this.thoiGianBatDau = thoiGianBatDau;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="thoi_gian_ket_thuc", length=10)
    public Date getThoiGianKetThuc() {
        return this.thoiGianKetThuc;
    }
    
    public void setThoiGianKetThuc(Date thoiGianKetThuc) {
        this.thoiGianKetThuc = thoiGianKetThuc;
    }

    
    @Column(name="trang_thai", nullable=false)
    public boolean isTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(boolean trangThai) {
        this.trangThai = trangThai;
    }




}


