package entities;
// Generated Mar 16, 2018 1:43:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SinhVien generated by hbm2java
 */
@Entity
@Table(name="sinh_vien"
    ,catalog="doantotnghiep"
)
public class SinhVien  implements java.io.Serializable {


     private int mssv;
     private Login login;
     private String hoTen;
     private String lop;
     private String khoaVien;
     private int khoa;
     private boolean gioiTinh;
     private String dienThoai;
     private String diaChi;
     private Date ngaySinh;
     private String avatar;
     private Set<SinhVienDiem> sinhVienDiems = new HashSet<SinhVienDiem>(0);
     private Set<SinhVienFile> sinhVienFiles = new HashSet<SinhVienFile>(0);
     private Set<SinhVienThucTap> sinhVienThucTaps = new HashSet<SinhVienThucTap>(0);
     private SinhVienInfo sinhVienInfo;

    public SinhVien() {
    }

	
    public SinhVien(int mssv, Login login, String hoTen, String lop, String khoaVien, int khoa, boolean gioiTinh, String dienThoai) {
        this.mssv = mssv;
        this.login = login;
        this.hoTen = hoTen;
        this.lop = lop;
        this.khoaVien = khoaVien;
        this.khoa = khoa;
        this.gioiTinh = gioiTinh;
        this.dienThoai = dienThoai;
    }
    public SinhVien(int mssv, Login login, String hoTen, String lop, String khoaVien, int khoa, boolean gioiTinh, String dienThoai, String diaChi, Date ngaySinh, String avatar, Set<SinhVienDiem> sinhVienDiems, Set<SinhVienFile> sinhVienFiles, Set<SinhVienThucTap> sinhVienThucTaps, SinhVienInfo sinhVienInfo) {
       this.mssv = mssv;
       this.login = login;
       this.hoTen = hoTen;
       this.lop = lop;
       this.khoaVien = khoaVien;
       this.khoa = khoa;
       this.gioiTinh = gioiTinh;
       this.dienThoai = dienThoai;
       this.diaChi = diaChi;
       this.ngaySinh = ngaySinh;
       this.avatar = avatar;
       this.sinhVienDiems = sinhVienDiems;
       this.sinhVienFiles = sinhVienFiles;
       this.sinhVienThucTaps = sinhVienThucTaps;
       this.sinhVienInfo = sinhVienInfo;
    }
   
     @Id 

    
    @Column(name="mssv", unique=true, nullable=false)
    public int getMssv() {
        return this.mssv;
    }
    
    public void setMssv(int mssv) {
        this.mssv = mssv;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="email", nullable=false)
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }

    
    @Column(name="ho_ten", nullable=false)
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    
    @Column(name="lop", nullable=false, length=50)
    public String getLop() {
        return this.lop;
    }
    
    public void setLop(String lop) {
        this.lop = lop;
    }

    
    @Column(name="khoa_vien", nullable=false)
    public String getKhoaVien() {
        return this.khoaVien;
    }
    
    public void setKhoaVien(String khoaVien) {
        this.khoaVien = khoaVien;
    }

    
    @Column(name="khoa", nullable=false)
    public int getKhoa() {
        return this.khoa;
    }
    
    public void setKhoa(int khoa) {
        this.khoa = khoa;
    }

    
    @Column(name="gioi_tinh", nullable=false)
    public boolean isGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(boolean gioiTinh) {
        this.gioiTinh = gioiTinh;
    }

    
    @Column(name="dien_thoai", nullable=false, length=15)
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }

    
    @Column(name="dia_chi", length=500)
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngay_sinh", length=10)
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }

    
    @Column(name="avatar", length=500)
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sinhVien")
    public Set<SinhVienDiem> getSinhVienDiems() {
        return this.sinhVienDiems;
    }
    
    public void setSinhVienDiems(Set<SinhVienDiem> sinhVienDiems) {
        this.sinhVienDiems = sinhVienDiems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sinhVien")
    public Set<SinhVienFile> getSinhVienFiles() {
        return this.sinhVienFiles;
    }
    
    public void setSinhVienFiles(Set<SinhVienFile> sinhVienFiles) {
        this.sinhVienFiles = sinhVienFiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sinhVien")
    public Set<SinhVienThucTap> getSinhVienThucTaps() {
        return this.sinhVienThucTaps;
    }
    
    public void setSinhVienThucTaps(Set<SinhVienThucTap> sinhVienThucTaps) {
        this.sinhVienThucTaps = sinhVienThucTaps;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="sinhVien")
    public SinhVienInfo getSinhVienInfo() {
        return this.sinhVienInfo;
    }
    
    public void setSinhVienInfo(SinhVienInfo sinhVienInfo) {
        this.sinhVienInfo = sinhVienInfo;
    }




}


