drop database doantotnghiep;
-- MySQL Script generated by MySQL Workbench
-- Fri Mar 16 11:24:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema doantotnghiep
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema doantotnghiep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `doantotnghiep` DEFAULT CHARACTER SET utf8 ;
USE `doantotnghiep` ;

-- -----------------------------------------------------
-- Table `doantotnghiep`.`cong_ty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`cong_ty` (
  `ma_cong_ty` INT(9) NOT NULL AUTO_INCREMENT,
  `ten_cong_ty` VARCHAR(500) CHARACTER SET 'utf8' NOT NULL,
  `dia_chi` VARCHAR(500) CHARACTER SET 'utf8' NOT NULL,
  `dien_thoai` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `website` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `linh_vung_hoat_dong` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `mo_ta` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `logo` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `trang_thai` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ma_cong_ty`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`login` (
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `pass` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `rule` INT(1) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`dai_dien_cong_ty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`dai_dien_cong_ty` (
  `ma_dai_dien` INT(9) NOT NULL AUTO_INCREMENT,
  `ma_cong_ty` INT(9) NOT NULL,
  `ho_ten` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `chuc_vu` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `dia_chi` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `dien_thoai` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `avatar` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`ma_dai_dien`),
  CONSTRAINT `dai_dien_cong_ty_ibfk_1`
    FOREIGN KEY (`ma_cong_ty`)
    REFERENCES `doantotnghiep`.`cong_ty` (`ma_cong_ty`),
  CONSTRAINT `dai_dien_cong_ty_ibfk_2`
    FOREIGN KEY (`email`)
    REFERENCES `doantotnghiep`.`login` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`giang_vien_huong_dan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`giang_vien_huong_dan` (
  `ma_gvhd` INT(9) NOT NULL AUTO_INCREMENT,
  `ma_cong_ty` INT(9) NOT NULL,
  `ho_ten` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `chucvu` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `dien_thoai` VARCHAR(15) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `avatar` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `dia_chi` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `linh_vuc_hoat_dong` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `du_an` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`ma_gvhd`),
  CONSTRAINT `giang_vien_huong_dan_ibfk_1`
    FOREIGN KEY (`ma_cong_ty`)
    REFERENCES `doantotnghiep`.`cong_ty` (`ma_cong_ty`),
  CONSTRAINT `giang_vien_huong_dan_ibfk_2`
    FOREIGN KEY (`email`)
    REFERENCES `doantotnghiep`.`login` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`de_tai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`de_tai` (
  `ma_de_tai` INT(9) NOT NULL AUTO_INCREMENT,
  `ma_cong_ty` INT(9) NOT NULL,
  `ma_gvhd` INT(9) NOT NULL,
  `ten_de_tai` VARCHAR(500) CHARACTER SET 'utf8' NOT NULL,
  `noi_dung` TEXT CHARACTER SET 'utf8' NOT NULL,
  `yeu_cau` TEXT CHARACTER SET 'utf8' NOT NULL,
  `nguoi_dang` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `so_luong` INT(3) NOT NULL,
  `so_luong_con` INT(3) NULL DEFAULT NULL,
  `trang_thai` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ma_de_tai`),
  CONSTRAINT `de_tai_ibfk_2`
    FOREIGN KEY (`ma_gvhd`)
    REFERENCES `doantotnghiep`.`giang_vien_huong_dan` (`ma_gvhd`),
  CONSTRAINT `de_tai_ibfk_1`
    FOREIGN KEY (`ma_cong_ty`)
    REFERENCES `doantotnghiep`.`cong_ty` (`ma_cong_ty`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`email` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `tieu_de` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `noi_dung` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `nguoi_nhan` VARCHAR(1000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `thoi_gian` DATETIME NULL DEFAULT NULL,
  `trang_thai` BIT(1) NULL DEFAULT NULL,
  `nguoi_gui` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `email_ibfk_1`
    FOREIGN KEY (`nguoi_gui`)
    REFERENCES `doantotnghiep`.`login` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`giang_vien_phu_trach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`giang_vien_phu_trach` (
  `ma_gvpt` INT(9) NOT NULL AUTO_INCREMENT,
  `ho_ten` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `dia_chi` VARCHAR(500) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `dien_thoai` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `khoa_vien` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `bo_mon` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `cong_trinh_nghien_cuu` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `sach_xuat_ban` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `mon_giang_day` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `khac` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `avatar` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`ma_gvpt`),
  CONSTRAINT `giang_vien_phu_trach_ibfk_1`
    FOREIGN KEY (`email`)
    REFERENCES `doantotnghiep`.`login` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`he_so_diem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`he_so_diem` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `diem_phan_hoi` DOUBLE(2,2) NULL DEFAULT NULL,
  `diem_bcqt` DOUBLE(2,2) NULL DEFAULT NULL,
  `diem_qt` DOUBLE(2,2) NULL DEFAULT NULL,
  `diem_ck` DOUBLE(2,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`logs` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `thoi_gian` TIME NULL DEFAULT NULL,
  `ngay_thang` DATE NULL DEFAULT NULL,
  `nguoi_dung` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `noi_dung` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `logs_ibfk_1`
    FOREIGN KEY (`nguoi_dung`)
    REFERENCES `doantotnghiep`.`login` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`sinh_vien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`sinh_vien` (
  `mssv` INT(8) NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `ho_ten` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `lop` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `khoa_vien` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `khoa` INT(3) NOT NULL,
  `gioi_tinh` BIT(1) NOT NULL,
  `dien_thoai` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `dia_chi` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ngay_sinh` DATE NULL DEFAULT NULL,
  `avatar` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`mssv`),
  CONSTRAINT `sinh_vien_ibfk_1`
    FOREIGN KEY (`email`)
    REFERENCES `doantotnghiep`.`login` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`sinh_vien_dang_ky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`sinh_vien_dang_ky` (
  `id` INT(9) NOT NULL  AUTO_INCREMENT,
  `mssv` INT(8) NOT NULL,
  `ma_cong_ty` INT(9) NOT NULL,
  `ma_de_tai` INT(9) NOT NULL,
  `trang_thai` INT(1) NOT NULL,
   PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`sinh_vien_diem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`sinh_vien_diem` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `mssv` INT(8) NOT NULL,
  `diem_phan_hoi` DOUBLE(2,2) NULL DEFAULT NULL,
  `diem_bcqt` DOUBLE(2,2) NULL DEFAULT NULL,
  `diem_qua_trinh` DOUBLE(2,2) NULL DEFAULT NULL,
  `diem_cuoi_ky` DOUBLE(2,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `sinh_vien_diem_ibfk_1`
    FOREIGN KEY (`mssv`)
    REFERENCES `doantotnghiep`.`sinh_vien` (`mssv`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`sinh_vien_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`sinh_vien_file` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `mssv` INT(8) NOT NULL,
  `ten_file` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `mo_ta` VARCHAR(1000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `link` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `loai_file` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `sinh_vien_file_ibfk_1`
    FOREIGN KEY (`mssv`)
    REFERENCES `doantotnghiep`.`sinh_vien` (`mssv`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`sinh_vien_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`sinh_vien_info` (
  `mssv` INT(8) NOT NULL,
  `ngoai_ngu` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ky_nang_lt` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ny_nang_khac` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `muc_tieu` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `hoat_dong` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `giai_thuong` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `so_thich` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `du_an` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`mssv`),
  CONSTRAINT `sinh_vien_info_ibfk_1`
    FOREIGN KEY (`mssv`)
    REFERENCES `doantotnghiep`.`sinh_vien` (`mssv`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`sinh_vien_thuc_tap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`sinh_vien_thuc_tap` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `mssv` INT(8) NOT NULL,
  `ma_de_tai` INT(9) NOT NULL,
  `thoi_gian_bat_dau` DATE NULL DEFAULT NULL,
  `thoi_gian_ket_thuc` DATE NULL DEFAULT NULL,
  `trang_thai` BIT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `sinh_vien_thuc_tap_ibfk_1`
    FOREIGN KEY (`mssv`)
    REFERENCES `doantotnghiep`.`sinh_vien` (`mssv`),
  CONSTRAINT `sinh_vien_thuc_tap_ibfk_2`
    FOREIGN KEY (`ma_de_tai`)
    REFERENCES `doantotnghiep`.`de_tai` (`ma_de_tai`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`thong_bao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`thong_bao` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `tieu_de` VARCHAR(1000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `noi_dung` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `nguoi_dang` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `ngay_thang` DATETIME NULL DEFAULT NULL,
  `type` INT(11) NULL DEFAULT NULL COMMENT '0: thông báo\n1: banner',
  `photo_link` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `thong_bao_ibfk_1`
    FOREIGN KEY (`nguoi_dang`)
    REFERENCES `doantotnghiep`.`login` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
