package hust.sie.inpg12.sonnc.entities;
// Generated Mar 17, 2018 9:53:40 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DaiDienCongTy generated by hbm2java
 */
@Entity
@Table(name="dai_dien_cong_ty"
    ,catalog="doantotnghiep"
)
public class DaiDienCongTy  implements java.io.Serializable {


     private Integer maDaiDien;
     private CongTy congTy;
     private Login login;
     private String hoTen;
     private String chucVu;
     private String diaChi;
     private String dienThoai;
     private String avatar;

    public DaiDienCongTy() {
    }

	
    public DaiDienCongTy(CongTy congTy, Login login, String hoTen, String dienThoai) {
        this.congTy = congTy;
        this.login = login;
        this.hoTen = hoTen;
        this.dienThoai = dienThoai;
    }
    public DaiDienCongTy(CongTy congTy, Login login, String hoTen, String chucVu, String diaChi, String dienThoai, String avatar) {
       this.congTy = congTy;
       this.login = login;
       this.hoTen = hoTen;
       this.chucVu = chucVu;
       this.diaChi = diaChi;
       this.dienThoai = dienThoai;
       this.avatar = avatar;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ma_dai_dien", unique=true, nullable=false)
    public Integer getMaDaiDien() {
        return this.maDaiDien;
    }
    
    public void setMaDaiDien(Integer maDaiDien) {
        this.maDaiDien = maDaiDien;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ma_cong_ty", nullable=false)
    public CongTy getCongTy() {
        return this.congTy;
    }
    
    public void setCongTy(CongTy congTy) {
        this.congTy = congTy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="email", nullable=false)
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }

    
    @Column(name="ho_ten", nullable=false)
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    
    @Column(name="chuc_vu")
    public String getChucVu() {
        return this.chucVu;
    }
    
    public void setChucVu(String chucVu) {
        this.chucVu = chucVu;
    }

    
    @Column(name="dia_chi", length=65535)
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    
    @Column(name="dien_thoai", nullable=false, length=15)
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }

    
    @Column(name="avatar", length=500)
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }




}


