package hust.sie.inpg12.sonnc.entities;
// Generated Mar 25, 2018 2:40:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DeTai generated by hbm2java
 */
public class DeTai  implements java.io.Serializable {


     private Integer maDeTai;
     private CongTy congTy;
     private GiangVienHuongDan giangVienHuongDan;
     private int maCongTy;
     private int maGvhd;
     private String tenDeTai;
     private String noiDung;
     private String yeuCau;
     private String nguoiDang;
     private int soLuong;
     private Integer soLuongCon;
     private int trangThai;
     private Date ngayDang;
     private Date hanDangKy;
     private Set sinhVienThucTaps = new HashSet(0);

    public DeTai() {
    }

	
    public DeTai(CongTy congTy, GiangVienHuongDan giangVienHuongDan, String tenDeTai, String noiDung, String yeuCau, int soLuong, int trangThai, Date ngayDang, Date hanDangKy) {
        this.congTy = congTy;
        this.giangVienHuongDan = giangVienHuongDan;
        this.tenDeTai = tenDeTai;
        this.noiDung = noiDung;
        this.yeuCau = yeuCau;
        this.soLuong = soLuong;
        this.trangThai = trangThai;
        this.ngayDang = ngayDang;
        this.hanDangKy = hanDangKy;
    }
    public DeTai(CongTy congTy, GiangVienHuongDan giangVienHuongDan, int maCongTy, int maGvhd, String tenDeTai, String noiDung, String yeuCau, String nguoiDang, int soLuong, Integer soLuongCon, int trangThai, Date ngayDang, Date hanDangKy, Set sinhVienThucTaps) {
       this.congTy = congTy;
       this.giangVienHuongDan = giangVienHuongDan;
       this.maCongTy = maCongTy;
       this.maGvhd = maGvhd;
       this.tenDeTai = tenDeTai;
       this.noiDung = noiDung;
       this.yeuCau = yeuCau;
       this.nguoiDang = nguoiDang;
       this.soLuong = soLuong;
       this.soLuongCon = soLuongCon;
       this.trangThai = trangThai;
       this.ngayDang = ngayDang;
       this.hanDangKy = hanDangKy;
       this.sinhVienThucTaps = sinhVienThucTaps;
    }
   
    public Integer getMaDeTai() {
        return this.maDeTai;
    }
    
    public void setMaDeTai(Integer maDeTai) {
        this.maDeTai = maDeTai;
    }
    public CongTy getCongTy() {
        return this.congTy;
    }
    
    public void setCongTy(CongTy congTy) {
        this.congTy = congTy;
    }
    public GiangVienHuongDan getGiangVienHuongDan() {
        return this.giangVienHuongDan;
    }
    
    public void setGiangVienHuongDan(GiangVienHuongDan giangVienHuongDan) {
        this.giangVienHuongDan = giangVienHuongDan;
    }

    public int getMaCongTy() {
        return maCongTy;
    }

    public void setMaCongTy(int maCongTy) {
        this.maCongTy = maCongTy;
    }

    public int getMaGvhd() {
        return maGvhd;
    }

    public void setMaGvhd(int maGvhd) {
        this.maGvhd = maGvhd;
    }
    
    public String getTenDeTai() {
        return this.tenDeTai;
    }
    
    public void setTenDeTai(String tenDeTai) {
        this.tenDeTai = tenDeTai;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }
    public String getYeuCau() {
        return this.yeuCau;
    }
    
    public void setYeuCau(String yeuCau) {
        this.yeuCau = yeuCau;
    }
    public String getNguoiDang() {
        return this.nguoiDang;
    }
    
    public void setNguoiDang(String nguoiDang) {
        this.nguoiDang = nguoiDang;
    }
    public int getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }
    public Integer getSoLuongCon() {
        return this.soLuongCon;
    }
    
    public void setSoLuongCon(Integer soLuongCon) {
        this.soLuongCon = soLuongCon;
    }
    public int getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(int trangThai) {
        this.trangThai = trangThai;
    }
    public Date getNgayDang() {
        return this.ngayDang;
    }
    
    public void setNgayDang(Date ngayDang) {
        this.ngayDang = ngayDang;
    }
    public Date getHanDangKy() {
        return this.hanDangKy;
    }
    
    public void setHanDangKy(Date hanDangKy) {
        this.hanDangKy = hanDangKy;
    }
    public Set getSinhVienThucTaps() {
        return this.sinhVienThucTaps;
    }
    
    public void setSinhVienThucTaps(Set sinhVienThucTaps) {
        this.sinhVienThucTaps = sinhVienThucTaps;
    }




}


