package hust.sie.inpg12.sonnc.entities;
// Generated Mar 17, 2018 9:53:40 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Email generated by hbm2java
 */
@Entity
@Table(name="email"
    ,catalog="doantotnghiep"
)
public class Email  implements java.io.Serializable {


     private Integer id;
     private Login login;
     private String tieuDe;
     private String noiDung;
     private String nguoiNhan;
     private Date thoiGian;
     private Boolean trangThai;

    public Email() {
    }

	
    public Email(Login login) {
        this.login = login;
    }
    public Email(Login login, String tieuDe, String noiDung, String nguoiNhan, Date thoiGian, Boolean trangThai) {
       this.login = login;
       this.tieuDe = tieuDe;
       this.noiDung = noiDung;
       this.nguoiNhan = nguoiNhan;
       this.thoiGian = thoiGian;
       this.trangThai = trangThai;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nguoi_gui", nullable=false)
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }

    
    @Column(name="tieu_de", length=500)
    public String getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(String tieuDe) {
        this.tieuDe = tieuDe;
    }

    
    @Column(name="noi_dung", length=65535)
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }

    
    @Column(name="nguoi_nhan", length=1000)
    public String getNguoiNhan() {
        return this.nguoiNhan;
    }
    
    public void setNguoiNhan(String nguoiNhan) {
        this.nguoiNhan = nguoiNhan;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="thoi_gian", length=19)
    public Date getThoiGian() {
        return this.thoiGian;
    }
    
    public void setThoiGian(Date thoiGian) {
        this.thoiGian = thoiGian;
    }

    
    @Column(name="trang_thai")
    public Boolean getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(Boolean trangThai) {
        this.trangThai = trangThai;
    }




}


