package hust.sie.inpg12.sonnc.entities;
// Generated Mar 25, 2018 2:40:17 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Email generated by hbm2java
 */
public class Email implements java.io.Serializable {

    private Integer id;
    private Login login;
    private String nguoiGui;
    private String tieuDe;
    private String noiDung;
    private String nguoiNhan;
    private Date thoiGian;
    private Boolean trangThai;
    private Integer type;
    private Integer mssv;
    private Integer dotThucTap;

    public Email() {
    }

    public Email(Login login) {
        this.login = login;
    }

    public Email(Login login, String nguoiGui, String tieuDe, String noiDung, String nguoiNhan, Date thoiGian, Boolean trangThai) {
        this.login = login;
        this.nguoiGui = nguoiGui;
        this.tieuDe = tieuDe;
        this.noiDung = noiDung;
        this.nguoiNhan = nguoiNhan;
        this.thoiGian = thoiGian;
        this.trangThai = trangThai;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Login getLogin() {
        return this.login;
    }

    public void setLogin(Login login) {
        this.login = login;
    }

    public String getNguoiGui() {
        return nguoiGui;
    }

    public void setNguoiGui(String nguoiGui) {
        this.nguoiGui = nguoiGui;
    }

    public String getTieuDe() {
        return this.tieuDe;
    }

    public void setTieuDe(String tieuDe) {
        this.tieuDe = tieuDe;
    }

    public String getNoiDung() {
        return this.noiDung;
    }

    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }

    public String getNguoiNhan() {
        return this.nguoiNhan;
    }

    public void setNguoiNhan(String nguoiNhan) {
        this.nguoiNhan = nguoiNhan;
    }

    public Date getThoiGian() {
        return this.thoiGian;
    }

    public void setThoiGian(Date thoiGian) {
        this.thoiGian = thoiGian;
    }

    public Boolean getTrangThai() {
        return this.trangThai;
    }

    public void setTrangThai(Boolean trangThai) {
        this.trangThai = trangThai;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getMssv() {
        return mssv;
    }

    public void setMssv(Integer mssv) {
        this.mssv = mssv;
    }

    public Integer getDotThucTap() {
        return dotThucTap;
    }

    public void setDotThucTap(Integer dotThucTap) {
        this.dotThucTap = dotThucTap;
    }

}
