package hust.sie.inpg12.sonnc.entities;
// Generated Mar 25, 2018 2:40:17 PM by Hibernate Tools 4.3.1



/**
 * FileAll generated by hbm2java
 */
public class FileAll  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String tenFile;
     private String noiDung;
     private String link;
     private Integer loaiNguoiDung;

    public FileAll() {
    }

	
    public FileAll(String email) {
        this.email = email;
    }
    public FileAll(String email, String tenFile, String noiDung, String link, Integer loaiNguoiDung) {
       this.email = email;
       this.tenFile = tenFile;
       this.noiDung = noiDung;
       this.link = link;
       this.loaiNguoiDung = loaiNguoiDung;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTenFile() {
        return this.tenFile;
    }
    
    public void setTenFile(String tenFile) {
        this.tenFile = tenFile;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public Integer getLoaiNguoiDung() {
        return this.loaiNguoiDung;
    }
    
    public void setLoaiNguoiDung(Integer loaiNguoiDung) {
        this.loaiNguoiDung = loaiNguoiDung;
    }




}


