package hust.sie.inpg12.sonnc.entities;
// Generated Mar 16, 2018 1:46:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GiangVienHuongDan generated by hbm2java
 */
@Entity
@Table(name="giang_vien_huong_dan"
    ,catalog="doantotnghiep"
)
public class GiangVienHuongDan  implements java.io.Serializable {


     private Integer maGvhd;
     private CongTy congTy;
     private Login login;
     private String hoTen;
     private String chucvu;
     private String dienThoai;
     private String avatar;
     private String diaChi;
     private String linhVucHoatDong;
     private String duAn;
     private Set<DeTai> deTais = new HashSet<DeTai>(0);

    public GiangVienHuongDan() {
    }

	
    public GiangVienHuongDan(CongTy congTy, Login login, String hoTen) {
        this.congTy = congTy;
        this.login = login;
        this.hoTen = hoTen;
    }
    public GiangVienHuongDan(CongTy congTy, Login login, String hoTen, String chucvu, String dienThoai, String avatar, String diaChi, String linhVucHoatDong, String duAn, Set<DeTai> deTais) {
       this.congTy = congTy;
       this.login = login;
       this.hoTen = hoTen;
       this.chucvu = chucvu;
       this.dienThoai = dienThoai;
       this.avatar = avatar;
       this.diaChi = diaChi;
       this.linhVucHoatDong = linhVucHoatDong;
       this.duAn = duAn;
       this.deTais = deTais;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ma_gvhd", unique=true, nullable=false)
    public Integer getMaGvhd() {
        return this.maGvhd;
    }
    
    public void setMaGvhd(Integer maGvhd) {
        this.maGvhd = maGvhd;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ma_cong_ty", nullable=false)
    public CongTy getCongTy() {
        return this.congTy;
    }
    
    public void setCongTy(CongTy congTy) {
        this.congTy = congTy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="email", nullable=false)
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }

    
    @Column(name="ho_ten", nullable=false)
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    
    @Column(name="chucvu")
    public String getChucvu() {
        return this.chucvu;
    }
    
    public void setChucvu(String chucvu) {
        this.chucvu = chucvu;
    }

    
    @Column(name="dien_thoai", length=15)
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }

    
    @Column(name="avatar")
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    
    @Column(name="dia_chi", length=500)
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    
    @Column(name="linh_vuc_hoat_dong", length=65535)
    public String getLinhVucHoatDong() {
        return this.linhVucHoatDong;
    }
    
    public void setLinhVucHoatDong(String linhVucHoatDong) {
        this.linhVucHoatDong = linhVucHoatDong;
    }

    
    @Column(name="du_an", length=65535)
    public String getDuAn() {
        return this.duAn;
    }
    
    public void setDuAn(String duAn) {
        this.duAn = duAn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="giangVienHuongDan")
    public Set<DeTai> getDeTais() {
        return this.deTais;
    }
    
    public void setDeTais(Set<DeTai> deTais) {
        this.deTais = deTais;
    }




}


