package hust.sie.inpg12.sonnc.entities;
// Generated Mar 17, 2018 9:53:40 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GiangVienPhuTrach generated by hbm2java
 */
@Entity
@Table(name="giang_vien_phu_trach"
    ,catalog="doantotnghiep"
)
public class GiangVienPhuTrach  implements java.io.Serializable {


     private Integer maGvpt;
     private Login login;
     private String hoTen;
     private String diaChi;
     private String dienThoai;
     private String khoaVien;
     private String boMon;
     private String congTrinhNghienCuu;
     private String sachXuatBan;
     private String monGiangDay;
     private String khac;
     private String avatar;

    public GiangVienPhuTrach() {
    }

	
    public GiangVienPhuTrach(Login login, String hoTen, String diaChi, String dienThoai) {
        this.login = login;
        this.hoTen = hoTen;
        this.diaChi = diaChi;
        this.dienThoai = dienThoai;
    }
    public GiangVienPhuTrach(Login login, String hoTen, String diaChi, String dienThoai, String khoaVien, String boMon, String congTrinhNghienCuu, String sachXuatBan, String monGiangDay, String khac, String avatar) {
       this.login = login;
       this.hoTen = hoTen;
       this.diaChi = diaChi;
       this.dienThoai = dienThoai;
       this.khoaVien = khoaVien;
       this.boMon = boMon;
       this.congTrinhNghienCuu = congTrinhNghienCuu;
       this.sachXuatBan = sachXuatBan;
       this.monGiangDay = monGiangDay;
       this.khac = khac;
       this.avatar = avatar;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ma_gvpt", unique=true, nullable=false)
    public Integer getMaGvpt() {
        return this.maGvpt;
    }
    
    public void setMaGvpt(Integer maGvpt) {
        this.maGvpt = maGvpt;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="email", nullable=false)
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }

    
    @Column(name="ho_ten", nullable=false)
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    
    @Column(name="dia_chi", nullable=false, length=500)
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    
    @Column(name="dien_thoai", nullable=false, length=15)
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }

    
    @Column(name="khoa_vien", length=500)
    public String getKhoaVien() {
        return this.khoaVien;
    }
    
    public void setKhoaVien(String khoaVien) {
        this.khoaVien = khoaVien;
    }

    
    @Column(name="bo_mon", length=500)
    public String getBoMon() {
        return this.boMon;
    }
    
    public void setBoMon(String boMon) {
        this.boMon = boMon;
    }

    
    @Column(name="cong_trinh_nghien_cuu", length=65535)
    public String getCongTrinhNghienCuu() {
        return this.congTrinhNghienCuu;
    }
    
    public void setCongTrinhNghienCuu(String congTrinhNghienCuu) {
        this.congTrinhNghienCuu = congTrinhNghienCuu;
    }

    
    @Column(name="sach_xuat_ban", length=65535)
    public String getSachXuatBan() {
        return this.sachXuatBan;
    }
    
    public void setSachXuatBan(String sachXuatBan) {
        this.sachXuatBan = sachXuatBan;
    }

    
    @Column(name="mon_giang_day", length=65535)
    public String getMonGiangDay() {
        return this.monGiangDay;
    }
    
    public void setMonGiangDay(String monGiangDay) {
        this.monGiangDay = monGiangDay;
    }

    
    @Column(name="khac", length=65535)
    public String getKhac() {
        return this.khac;
    }
    
    public void setKhac(String khac) {
        this.khac = khac;
    }

    
    @Column(name="avatar", length=500)
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }




}


