package hust.sie.inpg12.sonnc.entities;
// Generated Mar 25, 2018 2:40:17 PM by Hibernate Tools 4.3.1



/**
 * HeSoDiem generated by hbm2java
 */
public class HeSoDiem  implements java.io.Serializable {


     private Integer id;
     private Double diemPhanHoi;
     private Double diemBcqt;
     private Double diemQt;
     private Double diemCk;

    public HeSoDiem() {
    }

    public HeSoDiem(Double diemPhanHoi, Double diemBcqt, Double diemQt, Double diemCk) {
       this.diemPhanHoi = diemPhanHoi;
       this.diemBcqt = diemBcqt;
       this.diemQt = diemQt;
       this.diemCk = diemCk;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Double getDiemPhanHoi() {
        return this.diemPhanHoi;
    }
    
    public void setDiemPhanHoi(Double diemPhanHoi) {
        this.diemPhanHoi = diemPhanHoi;
    }
    public Double getDiemBcqt() {
        return this.diemBcqt;
    }
    
    public void setDiemBcqt(Double diemBcqt) {
        this.diemBcqt = diemBcqt;
    }
    public Double getDiemQt() {
        return this.diemQt;
    }
    
    public void setDiemQt(Double diemQt) {
        this.diemQt = diemQt;
    }
    public Double getDiemCk() {
        return this.diemCk;
    }
    
    public void setDiemCk(Double diemCk) {
        this.diemCk = diemCk;
    }




}


