package hust.sie.inpg12.sonnc.entities;
// Generated Mar 16, 2018 1:46:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HeSoDiem generated by hbm2java
 */
@Entity
@Table(name="he_so_diem"
    ,catalog="doantotnghiep"
)
public class HeSoDiem  implements java.io.Serializable {


     private Integer id;
     private Double diemPhanHoi;
     private Double diemBcqt;
     private Double diemQt;
     private Double diemCk;

    public HeSoDiem() {
    }

    public HeSoDiem(Double diemPhanHoi, Double diemBcqt, Double diemQt, Double diemCk) {
       this.diemPhanHoi = diemPhanHoi;
       this.diemBcqt = diemBcqt;
       this.diemQt = diemQt;
       this.diemCk = diemCk;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="diem_phan_hoi", precision=2)
    public Double getDiemPhanHoi() {
        return this.diemPhanHoi;
    }
    
    public void setDiemPhanHoi(Double diemPhanHoi) {
        this.diemPhanHoi = diemPhanHoi;
    }

    
    @Column(name="diem_bcqt", precision=2)
    public Double getDiemBcqt() {
        return this.diemBcqt;
    }
    
    public void setDiemBcqt(Double diemBcqt) {
        this.diemBcqt = diemBcqt;
    }

    
    @Column(name="diem_qt", precision=2)
    public Double getDiemQt() {
        return this.diemQt;
    }
    
    public void setDiemQt(Double diemQt) {
        this.diemQt = diemQt;
    }

    
    @Column(name="diem_ck", precision=2)
    public Double getDiemCk() {
        return this.diemCk;
    }
    
    public void setDiemCk(Double diemCk) {
        this.diemCk = diemCk;
    }




}


