package hust.sie.inpg12.sonnc.entities;
// Generated Mar 25, 2018 2:40:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * NguoiHuongDan generated by hbm2java
 */
public class NguoiHuongDan  implements java.io.Serializable {


     private Integer maGvhd;
     private CongTy congTy;
     private Login login;
     private int maCongTy;
     private String email;
     private String hoTen;
     private String chucvu;
     private String dienThoai;
     private String avatar;
     private String diaChi;
     private String linhVucHoatDong;
     private String duAn;
     private Set deTais = new HashSet(0);

    public NguoiHuongDan() {
    }

	
    public NguoiHuongDan(CongTy congTy, Login login, String hoTen) {
        this.congTy = congTy;
        this.login = login;
        this.hoTen = hoTen;
    }
    public NguoiHuongDan(CongTy congTy, Login login, int maCongTy, String email, String hoTen, String chucvu, String dienThoai, String avatar, String diaChi, String linhVucHoatDong, String duAn, Set deTais) {
       this.congTy = congTy;
       this.login = login;
       this.maCongTy = maCongTy;
       this.email = email;
       this.hoTen = hoTen;
       this.chucvu = chucvu;
       this.dienThoai = dienThoai;
       this.avatar = avatar;
       this.diaChi = diaChi;
       this.linhVucHoatDong = linhVucHoatDong;
       this.duAn = duAn;
       this.deTais = deTais;
    }
   
    public Integer getMaGvhd() {
        return this.maGvhd;
    }
    
    public void setMaGvhd(Integer maGvhd) {
        this.maGvhd = maGvhd;
    }
    public CongTy getCongTy() {
        return this.congTy;
    }
    
    public void setCongTy(CongTy congTy) {
        this.congTy = congTy;
    }
    public Login getLogin() {
        return this.login;
    }

    public int getMaCongTy() {
        return maCongTy;
    }

    public void setMaCongTy(int maCongTy) {
        this.maCongTy = maCongTy;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getChucvu() {
        return this.chucvu;
    }
    
    public void setChucvu(String chucvu) {
        this.chucvu = chucvu;
    }
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getLinhVucHoatDong() {
        return this.linhVucHoatDong;
    }
    
    public void setLinhVucHoatDong(String linhVucHoatDong) {
        this.linhVucHoatDong = linhVucHoatDong;
    }
    public String getDuAn() {
        return this.duAn;
    }
    
    public void setDuAn(String duAn) {
        this.duAn = duAn;
    }
    public Set getDeTais() {
        return this.deTais;
    }
    
    public void setDeTais(Set deTais) {
        this.deTais = deTais;
    }




}


