package hust.sie.inpg12.sonnc.entities;
// Generated Mar 25, 2018 2:40:17 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * QuyTrinh generated by hbm2java
 */
public class QuyTrinh  implements java.io.Serializable {


     private Integer id;
     private String tieuDe;
     private String noiDung;
     private Date ngayBatDau;
     private Date ngayKetThuc;
//     private String maXacThuc;
//     private Integer trangThai;

    public QuyTrinh() {
    }

    public QuyTrinh(String tieuDe, String noiDung, Date ngayBatDau, Date ngayKetThuc) {
       this.tieuDe = tieuDe;
       this.noiDung = noiDung;
       this.ngayBatDau = ngayBatDau;
       this.ngayKetThuc = ngayKetThuc;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(String tieuDe) {
        this.tieuDe = tieuDe;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }
    public Date getNgayBatDau() {
        return this.ngayBatDau;
    }
    
    public void setNgayBatDau(Date ngayBatDau) {
        this.ngayBatDau = ngayBatDau;
    }
    public Date getNgayKetThuc() {
        return this.ngayKetThuc;
    }
    
    public void setNgayKetThuc(Date ngayKetThuc) {
        this.ngayKetThuc = ngayKetThuc;
    }

}


