package hust.sie.inpg12.sonnc.entities;
// Generated Mar 25, 2018 2:40:17 PM by Hibernate Tools 4.3.1



/**
 * SinhVienInfo generated by hbm2java
 */
public class SinhVienInfo  implements java.io.Serializable {


     private Integer id;
     private SinhVien sinhVien;
     private int mssv;
     private String ngoaiNgu;
     private String kyNangLt;
     private String kyNangKhac;
     private String mucTieu;
     private String hoatDong;
     private String giaiThuong;
     private String soThich;
     private String duAn;

    public SinhVienInfo() {
    }

	
    public SinhVienInfo(SinhVien sinhVien) {
        this.sinhVien = sinhVien;
    }
    public SinhVienInfo(SinhVien sinhVien, int mssv, String ngoaiNgu, String kyNangLt, String kyNangKhac, String mucTieu, String hoatDong, String giaiThuong, String soThich, String duAn) {
       this.sinhVien = sinhVien;
       this.mssv = mssv;
       this.ngoaiNgu = ngoaiNgu;
       this.kyNangLt = kyNangLt;
       this.kyNangKhac = kyNangKhac;
       this.mucTieu = mucTieu;
       this.hoatDong = hoatDong;
       this.giaiThuong = giaiThuong;
       this.soThich = soThich;
       this.duAn = duAn;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public SinhVien getSinhVien() {
        return this.sinhVien;
    }
    
    public void setSinhVien(SinhVien sinhVien) {
        this.sinhVien = sinhVien;
    }

    public int getMssv() {
        return mssv;
    }

    public void setMssv(int mssv) {
        this.mssv = mssv;
    }
    
    public String getNgoaiNgu() {
        return this.ngoaiNgu;
    }
    
    public void setNgoaiNgu(String ngoaiNgu) {
        this.ngoaiNgu = ngoaiNgu;
    }
    public String getKyNangLt() {
        return this.kyNangLt;
    }
    
    public void setKyNangLt(String kyNangLt) {
        this.kyNangLt = kyNangLt;
    }
    public String getKyNangKhac() {
        return this.kyNangKhac;
    }
    
    public void setKyNangKhac(String kyNangKhac) {
        this.kyNangKhac = kyNangKhac;
    }
    public String getMucTieu() {
        return this.mucTieu;
    }
    
    public void setMucTieu(String mucTieu) {
        this.mucTieu = mucTieu;
    }
    public String getHoatDong() {
        return this.hoatDong;
    }
    
    public void setHoatDong(String hoatDong) {
        this.hoatDong = hoatDong;
    }
    public String getGiaiThuong() {
        return this.giaiThuong;
    }
    
    public void setGiaiThuong(String giaiThuong) {
        this.giaiThuong = giaiThuong;
    }
    public String getSoThich() {
        return this.soThich;
    }
    
    public void setSoThich(String soThich) {
        this.soThich = soThich;
    }
    public String getDuAn() {
        return this.duAn;
    }
    
    public void setDuAn(String duAn) {
        this.duAn = duAn;
    }




}


