package hust.sie.inpg12.sonnc.entities;
// Generated Mar 25, 2018 2:40:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SinhVien generated by hbm2java
 */
public class SinhVien  implements java.io.Serializable {


     private int mssv;
     private Login login;
     private String email;
     private String hoTen;
     private String lop;
     private String khoaVien;
     private int khoa;
     private boolean gioiTinh;
     private String dienThoai;
     private String diaChi;
     private Date ngaySinh;
     private String avatar;
     private Boolean laptop;
     private Set sinhVienInfos = new HashSet(0);
     private Set sinhVienDiems = new HashSet(0);
     private Set sinhVienFiles = new HashSet(0);
     private Set sinhVienThucTaps = new HashSet(0);
     private String status;

    public SinhVien() {
    }

	
    public SinhVien(int mssv, Login login, String hoTen, String lop, String khoaVien, int khoa, boolean gioiTinh, String dienThoai) {
        this.mssv = mssv;
        this.login = login;
        this.hoTen = hoTen;
        this.lop = lop;
        this.khoaVien = khoaVien;
        this.khoa = khoa;
        this.gioiTinh = gioiTinh;
        this.dienThoai = dienThoai;
    }
    public SinhVien(int mssv, Login login, String email, String hoTen, String lop, String khoaVien, int khoa, boolean gioiTinh, String dienThoai, String diaChi, Date ngaySinh, String avatar, Boolean laptop, Set sinhVienInfos, Set sinhVienDiems, Set sinhVienFiles, Set sinhVienThucTaps) {
       this.mssv = mssv;
       this.email = email;
       this.login = login;
       this.hoTen = hoTen;
       this.lop = lop;
       this.khoaVien = khoaVien;
       this.khoa = khoa;
       this.gioiTinh = gioiTinh;
       this.dienThoai = dienThoai;
       this.diaChi = diaChi;
       this.ngaySinh = ngaySinh;
       this.avatar = avatar;
       this.laptop = laptop;
       this.sinhVienInfos = sinhVienInfos;
       this.sinhVienDiems = sinhVienDiems;
       this.sinhVienFiles = sinhVienFiles;
       this.sinhVienThucTaps = sinhVienThucTaps;
    }
   
    public int getMssv() {
        return this.mssv;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
    
    public void setMssv(int mssv) {
        this.mssv = mssv;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getLop() {
        return this.lop;
    }
    
    public void setLop(String lop) {
        this.lop = lop;
    }
    public String getKhoaVien() {
        return this.khoaVien;
    }
    
    public void setKhoaVien(String khoaVien) {
        this.khoaVien = khoaVien;
    }
    public int getKhoa() {
        return this.khoa;
    }
    
    public void setKhoa(int khoa) {
        this.khoa = khoa;
    }
    public boolean isGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(boolean gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    public Boolean getLaptop() {
        return this.laptop;
    }
    
    public void setLaptop(Boolean laptop) {
        this.laptop = laptop;
    }
    public Set getSinhVienInfos() {
        return this.sinhVienInfos;
    }
    
    public void setSinhVienInfos(Set sinhVienInfos) {
        this.sinhVienInfos = sinhVienInfos;
    }
    public Set getSinhVienDiems() {
        return this.sinhVienDiems;
    }
    
    public void setSinhVienDiems(Set sinhVienDiems) {
        this.sinhVienDiems = sinhVienDiems;
    }
    public Set getSinhVienFiles() {
        return this.sinhVienFiles;
    }
    
    public void setSinhVienFiles(Set sinhVienFiles) {
        this.sinhVienFiles = sinhVienFiles;
    }
    public Set getSinhVienThucTaps() {
        return this.sinhVienThucTaps;
    }
    
    public void setSinhVienThucTaps(Set sinhVienThucTaps) {
        this.sinhVienThucTaps = sinhVienThucTaps;
    }




}


