package hust.sie.inpg12.sonnc.entities;
// Generated Mar 17, 2018 9:53:40 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SinhVienDangKy generated by hbm2java
 */
@Entity
@Table(name="sinh_vien_dang_ky"
    ,catalog="doantotnghiep"
)
public class SinhVienDangKy  implements java.io.Serializable {


     private Integer id;
     private int mssv;
     private int maCongTy;
     private int maDeTai;
     private int trangThai;

    public SinhVienDangKy() {
    }

    public SinhVienDangKy(int mssv, int maCongTy, int maDeTai, int trangThai) {
       this.mssv = mssv;
       this.maCongTy = maCongTy;
       this.maDeTai = maDeTai;
       this.trangThai = trangThai;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="mssv", nullable=false)
    public int getMssv() {
        return this.mssv;
    }
    
    public void setMssv(int mssv) {
        this.mssv = mssv;
    }

    
    @Column(name="ma_cong_ty", nullable=false)
    public int getMaCongTy() {
        return this.maCongTy;
    }
    
    public void setMaCongTy(int maCongTy) {
        this.maCongTy = maCongTy;
    }

    
    @Column(name="ma_de_tai", nullable=false)
    public int getMaDeTai() {
        return this.maDeTai;
    }
    
    public void setMaDeTai(int maDeTai) {
        this.maDeTai = maDeTai;
    }

    
    @Column(name="trang_thai", nullable=false)
    public int getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(int trangThai) {
        this.trangThai = trangThai;
    }




}


