package hust.sie.inpg12.sonnc.entities;
// Generated Mar 25, 2018 2:40:17 PM by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * SinhVienDangKy generated by hbm2java
 */
public class SinhVienDangKy  implements java.io.Serializable {


     private Integer id;
     private int mssv;
     private int maCongTy;
     private int maDeTai;
     private int trangThai;
     private double soKhop;
     private Date ngayDangKy;
     private int dotThucTap;

    public SinhVienDangKy() {
    }

    public SinhVienDangKy(int mssv, int maCongTy, int maDeTai, int trangThai) {
       this.mssv = mssv;
       this.maCongTy = maCongTy;
       this.maDeTai = maDeTai;
       this.trangThai = trangThai;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getMssv() {
        return this.mssv;
    }
    
    public void setMssv(int mssv) {
        this.mssv = mssv;
    }
    public int getMaCongTy() {
        return this.maCongTy;
    }
    
    public void setMaCongTy(int maCongTy) {
        this.maCongTy = maCongTy;
    }
    public int getMaDeTai() {
        return this.maDeTai;
    }
    
    public void setMaDeTai(int maDeTai) {
        this.maDeTai = maDeTai;
    }
    public int getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(int trangThai) {
        this.trangThai = trangThai;
    }

    public double getSoKhop() {
        return soKhop;
    }

    public void setSoKhop(double soKhop) {
        this.soKhop = soKhop;
    }

    public Date getNgayDangKy() {
        return ngayDangKy;
    }

    public void setNgayDangKy(Date ngayDangKy) {
        this.ngayDangKy = ngayDangKy;
    }

    public int getDotThucTap() {
        return dotThucTap;
    }

    public void setDotThucTap(int dotThucTap) {
        this.dotThucTap = dotThucTap;
    }

    


}


