package hust.sie.inpg12.sonnc.entities;
// Generated Mar 17, 2018 9:53:40 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SinhVienFile generated by hbm2java
 */
@Entity
@Table(name="sinh_vien_file"
    ,catalog="doantotnghiep"
)
public class SinhVienFile  implements java.io.Serializable {


     private Integer id;
     private SinhVien sinhVien;
     private String tenFile;
     private String moTa;
     private String link;
     private Integer loaiFile;

    public SinhVienFile() {
    }

	
    public SinhVienFile(SinhVien sinhVien) {
        this.sinhVien = sinhVien;
    }
    public SinhVienFile(SinhVien sinhVien, String tenFile, String moTa, String link, Integer loaiFile) {
       this.sinhVien = sinhVien;
       this.tenFile = tenFile;
       this.moTa = moTa;
       this.link = link;
       this.loaiFile = loaiFile;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mssv", nullable=false)
    public SinhVien getSinhVien() {
        return this.sinhVien;
    }
    
    public void setSinhVien(SinhVien sinhVien) {
        this.sinhVien = sinhVien;
    }

    
    @Column(name="ten_file", length=500)
    public String getTenFile() {
        return this.tenFile;
    }
    
    public void setTenFile(String tenFile) {
        this.tenFile = tenFile;
    }

    
    @Column(name="mo_ta", length=1000)
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }

    
    @Column(name="link", length=500)
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }

    
    @Column(name="loai_file")
    public Integer getLoaiFile() {
        return this.loaiFile;
    }
    
    public void setLoaiFile(Integer loaiFile) {
        this.loaiFile = loaiFile;
    }




}


