package hust.sie.inpg12.sonnc.entities;
// Generated Mar 25, 2018 2:40:17 PM by Hibernate Tools 4.3.1



/**
 * SinhVienFile generated by hbm2java
 */
public class SinhVienFile  implements java.io.Serializable {


     private Integer id;
     private SinhVien sinhVien;
     private int mssv;
     private String tenFile;
     private String moTa;
     private String link;
     private Integer loaiFile;

    public SinhVienFile() {
    }

	
    public SinhVienFile(SinhVien sinhVien) {
        this.sinhVien = sinhVien;
    }
    public SinhVienFile(SinhVien sinhVien, int mssv, String tenFile, String moTa, String link, Integer loaiFile) {
       this.sinhVien = sinhVien;
       this.mssv = mssv;
       this.tenFile = tenFile;
       this.moTa = moTa;
       this.link = link;
       this.loaiFile = loaiFile;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public SinhVien getSinhVien() {
        return this.sinhVien;
    }
    
    public void setSinhVien(SinhVien sinhVien) {
        this.sinhVien = sinhVien;
    }

    public int getMssv() {
        return mssv;
    }

    public void setMssv(int mssv) {
        this.mssv = mssv;
    }
    
    public String getTenFile() {
        return this.tenFile;
    }
    
    public void setTenFile(String tenFile) {
        this.tenFile = tenFile;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public Integer getLoaiFile() {
        return this.loaiFile;
    }
    
    public void setLoaiFile(Integer loaiFile) {
        this.loaiFile = loaiFile;
    }




}


