package hust.sie.inpg12.sonnc.entities;
// Generated Mar 25, 2018 2:40:17 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SinhVienThucTap generated by hbm2java
 */
public class SinhVienThucTap  implements java.io.Serializable {


     private Integer id;
     private DeTai deTai;
     private SinhVien sinhVien;
     private int maDeTai;
     private int mssv;
     private Date thoiGianBatDau;
     private Date thoiGianKetThuc;
     private boolean trangThai;
     private int dotThucTap;

    public SinhVienThucTap() {
    }

	
    public SinhVienThucTap(DeTai deTai, SinhVien sinhVien, boolean trangThai, int dotThucTap) {
        this.deTai = deTai;
        this.sinhVien = sinhVien;
        this.trangThai = trangThai;
        this.dotThucTap = dotThucTap;
    }
    public SinhVienThucTap(DeTai deTai, SinhVien sinhVien, int maDeTai, int mssv, Date thoiGianBatDau, Date thoiGianKetThuc, boolean trangThai, int dotThucTap) {
       this.deTai = deTai;
       this.sinhVien = sinhVien;
       this.maDeTai = maDeTai;
       this.mssv = mssv;
       this.thoiGianBatDau = thoiGianBatDau;
       this.thoiGianKetThuc = thoiGianKetThuc;
       this.trangThai = trangThai;
       this.dotThucTap = dotThucTap;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public DeTai getDeTai() {
        return this.deTai;
    }
    
    public void setDeTai(DeTai deTai) {
        this.deTai = deTai;
    }
    public SinhVien getSinhVien() {
        return this.sinhVien;
    }
    
    public void setSinhVien(SinhVien sinhVien) {
        this.sinhVien = sinhVien;
    }

    public int getMaDeTai() {
        return maDeTai;
    }

    public void setMaDeTai(int maDeTai) {
        this.maDeTai = maDeTai;
    }

    public int getMssv() {
        return mssv;
    }

    public void setMssv(int mssv) {
        this.mssv = mssv;
    }
    
    public Date getThoiGianBatDau() {
        return this.thoiGianBatDau;
    }
    
    public void setThoiGianBatDau(Date thoiGianBatDau) {
        this.thoiGianBatDau = thoiGianBatDau;
    }
    public Date getThoiGianKetThuc() {
        return this.thoiGianKetThuc;
    }
    
    public void setThoiGianKetThuc(Date thoiGianKetThuc) {
        this.thoiGianKetThuc = thoiGianKetThuc;
    }
    public boolean isTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(boolean trangThai) {
        this.trangThai = trangThai;
    }
    public int getDotThucTap() {
        return this.dotThucTap;
    }
    
    public void setDotThucTap(int dotThucTap) {
        this.dotThucTap = dotThucTap;
    }




}


