package hust.sie.inpg12.sonnc.entities;
// Generated Mar 17, 2018 9:53:40 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThongBao generated by hbm2java
 */
@Entity
@Table(name="thong_bao"
    ,catalog="doantotnghiep"
)
public class ThongBao  implements java.io.Serializable {


     private Integer id;
     private Login login;
     private String tieuDe;
     private String noiDung;
     private Date ngayThang;
     private Integer type;
     private String photoLink;

    public ThongBao() {
    }

	
    public ThongBao(Login login) {
        this.login = login;
    }
    public ThongBao(Login login, String tieuDe, String noiDung, Date ngayThang, Integer type, String photoLink) {
       this.login = login;
       this.tieuDe = tieuDe;
       this.noiDung = noiDung;
       this.ngayThang = ngayThang;
       this.type = type;
       this.photoLink = photoLink;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nguoi_dang", nullable=false)
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }

    
    @Column(name="tieu_de", length=1000)
    public String getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(String tieuDe) {
        this.tieuDe = tieuDe;
    }

    
    @Column(name="noi_dung", length=65535)
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ngay_thang", length=19)
    public Date getNgayThang() {
        return this.ngayThang;
    }
    
    public void setNgayThang(Date ngayThang) {
        this.ngayThang = ngayThang;
    }

    
    @Column(name="type")
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }

    
    @Column(name="photo_link", length=500)
    public String getPhotoLink() {
        return this.photoLink;
    }
    
    public void setPhotoLink(String photoLink) {
        this.photoLink = photoLink;
    }




}


