package hust.sie.inpg12.sonnc.entities;
// Generated Mar 25, 2018 2:40:17 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ThongBao generated by hbm2java
 */
public class ThongBao  implements java.io.Serializable {


     private Integer id;
     private Login login;
     private String nguoiDang;
     private String tieuDe;
     private String noiDung;
     private Date ngayThang;
     private Integer type;
     private String photoLink;

    public ThongBao() {
    }

	
    public ThongBao(Login login) {
        this.login = login;
    }
    public ThongBao(Login login, String nguoiDang, String tieuDe, String noiDung, Date ngayThang, Integer type, String photoLink) {
       this.login = login;
       this.nguoiDang = nguoiDang;
       this.tieuDe = tieuDe;
       this.noiDung = noiDung;
       this.ngayThang = ngayThang;
       this.type = type;
       this.photoLink = photoLink;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }

    public String getNguoiDang() {
        return nguoiDang;
    }

    public void setNguoiDang(String nguoiDang) {
        this.nguoiDang = nguoiDang;
    }
    
    public String getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(String tieuDe) {
        this.tieuDe = tieuDe;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }
    public Date getNgayThang() {
        return this.ngayThang;
    }
    
    public void setNgayThang(Date ngayThang) {
        this.ngayThang = ngayThang;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public String getPhotoLink() {
        return this.photoLink;
    }
    
    public void setPhotoLink(String photoLink) {
        this.photoLink = photoLink;
    }




}


